### ISSUE TITLE
cJson.h . I must be missing something as I can't find this file in the source tree

### ISSUE THREAD

**Issue by skieast** [danjulio/lepton#19]
I copied cJson.h and cJson.c from https://github.com/DaveGamble/cJSON to the components/cmd folder. Not sure where it was supposed to be.

**Comment by danjulio** [comment]
They should be part of the IDF.  I see them in components/json.

**Comment by skieast** [comment]
Yes, As I am building with idf.py (cmake) all the components used have to be listed. I'll do that and it should work. Thanks
