### ISSUE TITLE
Mobile App

### ISSUE THREAD

**Issue by Andi68-at** [danjulio/lepton#24]
Hello Will there be an Android app for tCam-mini in the future? The desktop app works flawlessly, but a mobile app would be much better. I use tCam-mini on a drone for fawn tracking. Thanks for the great development.

**Comment by danjulio** [comment]
I hope so!  I'm an Android user too.  The development environment I use for application/app development is now just getting Android support but at the moment they don't support sockets.  As soon as they have a beta that does I will try to port the iOS app.  I am hoping this happens this year but unfortunately they haven't put out a timeline.
