### ISSUE TITLE
tCam-Mini maximum Wifi password length should be 64, not 32

### ISSUE THREAD

**Issue by hoberman** [danjulio/lepton#36]
Wifi specs allow for a maximum password length of 63 characters (or a 64-character hex PSK), but the tCam-Mini ps_utilities.h file sets a limit of 32 characters. The tCam Console app (MacOS, maybe others) appears to be limiting the length to 32 characters as well.

#define PS_PW_MAX_LEN       32

**Comment by danjulio** [comment]
Ok.  I'll try to get this in the next set of releases.

**Comment by danjulio** [comment]
Hello hoberman, the new V3.1 firmware (and all the supporting software - desktop and iOS) now support 63 character passwords.
