### ISSUE TITLE
Change default palette in the Lepton Module

### ISSUE THREAD

**Issue by kami83** [danjulio/lepton#39]
Hi Dan,

just a question not directly for your program.
Do you know how it is possible to change the defaul palette in the Lepton Module. Maybe with your Software and Hardware?

My problem is that if i use the module over USB in the Purethermal board for example VLC only display the Video in RAINBOWS Table and i want IRON.

How can i change the default.

Thanks a lot for some help.

BR Stefan

**Comment by danjulio** [comment]
I'm sorry, I can't answer this question as I don't know details about this device.  Probably a question for Group Gets.  I think they share the source so perhaps you can find where the default is set, change that and compile your own version.

**Comment by kami83** [comment]
HI, thanks a lot. I will do it like this.

BR Stefan
