### ISSUE TITLE
Image Analysis in FLIR TOOLS

### ISSUE THREAD

**Issue by Morph-123** [danjulio/lepton#44]
Hi Dan,
Your program was very helpful for me, thanks for creating this.
Across the process a doubt came across that are you able to see metadata of thermal images in FLIR TOOLS software.

**Comment by danjulio** [comment]
Hello Morph-123, I'm glad my program has been helpful.  Unfortunately I don't have the ability to read the metadata from images generated by FLIR tools.  I'm not sure I've even seen documentation that describes it.

**Comment by Morph-123** [comment]
Can you guide me about, what approach should I try to get the metadata in Flir tools using ATLAS SDK in R PI

**Comment by danjulio** [comment]
No, I'm sorry.  I can't help.  I don't know anything about any of that.
